const REDIS_KEY_STOCKS_HASH = 'stocks';
const REDIS_KEY_STOCK_CANDLE_LIVE_PREFIX = 'stock:candles:live';

const REDIS_CHANNEL_ORDERBOOK_PREFIX = 'stock:order-book';
const REDIS_CHANNEL_TRADE_PREFIX = 'stock:trade';
const REDIS_CHANNEL_CANDLE_PREFIX = 'stock:candle';
const REDIS_CHANNEL_CANDLE_UPDATE = 'candle:update';
const REDIS_CHANNEL_ORDER_UPDATE = 'order:update';

const REDIS_STREAM = 'STREAMS';
const REDIS_STREAM_GROUP = 'GROUP';
const REDIS_STREAM_GROUP_NAME = 'order';
const REDIS_STREAM_CONSUMER_NAME = 'order-matcher';
const REDIS_STREAM_BLOCK = 'BLOCK';
const REDIS_STREAM_BLOCK_DURATION_MILISECOND = 5000;
const REDIS_STREAM_ORDER_PROCESS = 'order:process';
const REDIS_STREAM_ORDER_CANCEL = 'order:cancel';
const REDIS_STREAM_ID = '>';



export {
    REDIS_STREAM_ID,
    REDIS_STREAM_ORDER_CANCEL,
    REDIS_STREAM_ORDER_PROCESS,
    REDIS_STREAM,
    REDIS_STREAM_BLOCK_DURATION_MILISECOND,
    REDIS_STREAM_BLOCK,
    REDIS_STREAM_GROUP,
    REDIS_STREAM_CONSUMER_NAME,
    REDIS_STREAM_GROUP_NAME,
    REDIS_CHANNEL_ORDER_UPDATE,
    REDIS_CHANNEL_CANDLE_UPDATE,
    REDIS_KEY_STOCK_CANDLE_LIVE_PREFIX,
    REDIS_KEY_STOCKS_HASH,
    REDIS_CHANNEL_ORDERBOOK_PREFIX,
    REDIS_CHANNEL_CANDLE_PREFIX,
    REDIS_CHANNEL_TRADE_PREFIX
};