const ROOM_PREFIX_CANDLE = 'candle';
const ROOM_PREFIX_TRADE = 'trade';
const ROOM_PREFIX_ORDERBOOK = 'order-book';

const REDIS_KEY_STOCKS_HASH = 'stocks';

const WS_EVENT_CONNECTION = 'connection';
const WS_EVENT_DISCONNECT = 'disconnect';
const WS_EVENT_CANDLE_INIT = 'candle:init';
const WS_EVENT_ROOM_JOIN = 'room:join';
const WS_EVENT_LEAVE_ROOM = 'room:left';
const WS_EVENT_ORDERBOOK = 'order-book';
const WS_EVENT_CANDLE_UPDATE = 'candle:update';
const WS_EVENT_TRADE = 'trade';
const ES_EVENT_ORDER_EXECUTION_UPDATE = 'order:execution:update';

const REDIS_CHANNEL_ORDERBOOK_PATTERN = 'stock:order-book:*';
const REDIS_CHANNEL_TRADE_PATTERN = 'stock:trade:*';
const REDIS_CHANNEL_CANDLE_PATTERN = 'stock:candle:*';
const REDIS_CHANNEL_CANDLE_UPDATE = 'candle:update';
const REDIS_CHANNEL_ORDER_UPDATE = 'order:update';
const REDIS_CHANNEL_PATTERNS = [
    REDIS_CHANNEL_ORDERBOOK_PATTERN,
    REDIS_CHANNEL_TRADE_PATTERN,
    REDIS_CHANNEL_CANDLE_PATTERN
];

export {
    WS_EVENT_CANDLE_INIT,
    WS_EVENT_CONNECTION,
    WS_EVENT_DISCONNECT,
    WS_EVENT_LEAVE_ROOM,
    REDIS_CHANNEL_ORDER_UPDATE,
    REDIS_CHANNEL_CANDLE_UPDATE,
    ES_EVENT_ORDER_EXECUTION_UPDATE,
    WS_EVENT_TRADE,
    WS_EVENT_CANDLE_UPDATE,
    WS_EVENT_ORDERBOOK,
    ROOM_PREFIX_CANDLE,
    ROOM_PREFIX_TRADE,
    ROOM_PREFIX_ORDERBOOK,
    REDIS_KEY_STOCKS_HASH,
    WS_EVENT_ROOM_JOIN,
    REDIS_CHANNEL_PATTERNS,
    REDIS_CHANNEL_CANDLE_PATTERN,
    REDIS_CHANNEL_ORDERBOOK_PATTERN,
    REDIS_CHANNEL_TRADE_PATTERN
};